#!/usr/bin/env python3
"""
plot_eta_snapshot.py
Plot the instantaneous free surface eta(x) over the bathymetry at a chosen time.

Reads:
    bot.txt   — bottom level (positive downward, generated by make_bathy.py)
    wlev.mat  — BLOCK output from SWASH (LAYOUT 3, WATL)

Usage:
    edit T_PLOT below, then `python3 plot_eta_snapshot.py`
"""
#%%
import re
import numpy as np
import matplotlib.pyplot as plt
from scipy.io import loadmat

# -------------------------------------------------------------- params
T_PLOT  = 200.0          # requested snapshot time              [s]
DX      = 1.0            # grid spacing                         [m]
L_DOM   = 600.0          # domain length                        [m]
H0      = 10.0           # max offshore depth (for plot limits) [m]
WLEVFILE = "wlev.mat"
BOTFILE  = "bot.txt"

# -------------------------------------------------------------- bathy
zb = np.loadtxt(BOTFILE).ravel()        # positive downward
x  = np.arange(zb.size) * DX            # cell-centred x coordinate
bed_z = -zb                             # z elevation of the bed (negative)

# -------------------------------------------------------------- read .mat
data = loadmat(WLEVFILE)

# discover SWASH variable names (Watlev_<time>) and sort by encoded time
def parse_swash_time(key):
    """Return simulation time [s] from a SWASH variable name like
       'Watlev_001000_000' (HHMMSS_sss) or 'Watlev_001000'."""
    m = re.search(r"_(\d{2})(\d{2})(\d{2})(?:_(\d{1,3}))?$", key)
    if not m:
        return None
    h, mn, s, sub = m.groups()
    t = int(h)*3600 + int(mn)*60 + int(s)
    if sub:
        t += int(sub) / 10**len(sub)
    return t

keys  = [k for k in data.keys() if k.lower().startswith("watl")]
times = np.array([parse_swash_time(k) for k in keys], dtype=float)
order = np.argsort(times)
keys, times = [keys[i] for i in order], times[order]

if not keys:
    raise SystemExit(f"No WATL variables found in {WLEVFILE}.  "
                     f"Got keys: {list(data.keys())}")

idx       = int(np.argmin(np.abs(times - T_PLOT)))
key, tnow = keys[idx], times[idx]
eta       = np.array(data[key]).ravel()

print(f"plotting WATL  →  requested t = {T_PLOT:.1f} s,  "
      f"closest in file = {tnow:.2f} s  (key '{key}')")

# -------------------------------------------------------------- plot
fig, ax = plt.subplots(figsize=(6, 3),dpi=300)

bed_bottom = -H0
# bed (brown fill below the bed)
ax.fill_between(x, bed_z, bed_bottom, color="wheat", alpha=0.7, label="")
# free surface
ax.plot(x, eta, color="#065A82", lw=1.8, label=f"η(x)  at t = {tnow:.1f} s")
# still water reference
ax.axhline(0., color="#5B6B7C", lw=0.8, ls="--", alpha=0.7, label="SWL")
# bed line (sharp)
ax.plot(x, bed_z, color="#5A3A24", lw=0.9, alpha=0.9)

ax.set_xlabel("x  [m]")
ax.set_ylabel("z  [m]")
ax.set_title(f"Free surface and bathymetry at t = {tnow:.1f} s",loc='left')
ax.set_xlim(0., L_DOM)
ax.set_ylim(bed_bottom, 2.5)
ax.legend(loc="best", fontsize=9)
ax.grid(alpha=0.25)
fig.tight_layout()
fname = f"eta_t{int(round(tnow)):04d}.png"
fig.savefig(fname, dpi=140)
print(f"wrote {fname}")
plt.show()
# %%
