"""
plot_eta.py
Plot the instantaneous free surface eta(x) over the bathymetry at a chosen time.

Reads:
    bot.txt   — bottom level (positive downward, generated by make_bathy.py)
    wlev.txt  — BLOCK ASCII output from SWASH (LAYOUT 3, WATL)
                each row is one time step: nx values of water level [m]

Usage:
    edit T_PLOT below, then `python3 plot_eta_snapshot.py`
"""
#%%
import numpy as np
import matplotlib.pyplot as plt

# ── params (must match input.sws) ──────────────────────────────────────
T_START  = 100.0    # first output time [s]  (OUTPUT 000100.000)
DT_OUT   = 1.0      # output interval   [s]
DX       = 1.0      # grid spacing      [m]
T_PLOT   = 500.0    # requested snapshot time [s]
T_PLOT   = T_START + T_PLOT  # absolute time to plot

# ── bathymetry ──────────────────────────────────────────────────────────
bathy = np.loadtxt("bot.txt").ravel()
x     = np.arange(bathy.size) * DX
nx    = len(bathy)

# ── helper: read SWASH BLOCK ASCII (any number of values per line) ──────
def read_block(path):
    """Read a SWASH BLOCK ASCII file into a flat float array."""
    with open(path) as f:
        return np.fromstring(f.read(), sep=' ')

# ── water level:  wlev.txt ────────────────────────────────────────────
vals   = read_block("wlev.txt")           # flat 1-D
n_times = len(vals) // nx
wlev   = vals.reshape(n_times, nx)        # (n_times, nx)
times  = T_START + np.arange(n_times) * DT_OUT
it = int(np.argmin(np.abs(times - T_START - T_PLOT)))

# ── velocity:  vel.txt ────────────────────────────────────────────────
# SWASH BLOCK layout per time step with 'VELK VEL':
#   VELK: 2*NLEV rows alternating  u_k1, v_k1, u_k2, v_k2, ..., u_kN, v_kN
#   VEL:  1 row  — depth-averaged velocity magnitude
#   total rows per time step = 2*NLEV + 1
vals_v     = read_block("vel.txt")
rows_per_t = len(vals_v) // (n_times * nx)   # = 2*NLEV + 1
NLEV       = (rows_per_t - 1) // 2           # auto-detected number of layers
vel_raw    = vals_v.reshape(n_times, rows_per_t, nx)

velk_u = vel_raw[:, 0:2*NLEV:2, :]   # (n_times, NLEV, nx) cross-shore velocity
velk_v = vel_raw[:, 1:2*NLEV:2, :]   # (n_times, NLEV, nx) along-shore (0 in 1D)
vel    = vel_raw[:, 2*NLEV,     :]   # (n_times, nx)        depth-averaged magnitude

# ── quick check ─────────────────────────────────────────────────────────
print(f"x      : {x.shape}   {x[0]:.0f} – {x[-1]:.0f} m")
print(f"times  : {times.shape}   {times[0]:.1f} – {times[-1]:.1f} s")
print(f"wlev   : {wlev.shape}")
print(f"NLEV   : {NLEV}   (auto-detected)")
print(f"velk_u : {velk_u.shape}   (n_times, n_layers, nx) cross-shore")
print(f"vel    : {vel.shape}    (n_times, nx) depth-averaged")

#%% PLOT
fig, ax = plt.subplots(figsize=(6, 3),dpi=300)

ax.plot(x, wlev[it,:], color="blue", lw=1.8, label=f"η(x)  at t = {T_PLOT:.1f} s")
ax.axhline(0., color="gray", lw=0.8, ls="--", alpha=0.7, label="SWL")
ax.plot(x, -bathy, color="black", lw=1.5, alpha=0.9)

ax.set_xlabel("x  [m]")
ax.set_ylabel("z  [m]")
ax.set_title(f"Free surface and bathymetry at t = {T_PLOT:.1f} s",loc='left')
ax.set_xlim(0., 600)
ax.set_ylim(-8, 2.5)
ax.legend(loc="best", fontsize=9)
ax.grid(alpha=0.25)
fig.tight_layout()
fname = f"eta_t{int(round(T_PLOT)):04d}.png"
fig.savefig(fname, dpi=140)
print(f"wrote {fname}")
plt.show()
# %%
