#!/usr/bin/env python3
"""
plot_velocity_snapshot.py
Plot the instantaneous depth-averaged horizontal velocity u(x) at a chosen time,
with the free-surface profile shown above for spatial context.

Reads:
    bot.txt   — bottom level (positive downward, generated by make_bathy.py)
    wlev.mat  — BLOCK output from SWASH (LAYOUT 3, WATL)   — for context
    vel.mat   — BLOCK output from SWASH (LAYOUT 3, VEL )

Usage:
    edit T_PLOT below, then `python3 plot_velocity_snapshot.py`

Notes:
    SWASH writes a separate variable per time step.  Variable names follow
    the SWASH convention: 'Watlev_<HHMMSS_sss>' for water level, and either
    'Velkx_<...>' / 'Velky_<...>' or 'Vksixs_<...>' / 'Vksys_<...>'  for the
    horizontal velocity components.  This script picks them by prefix.
"""
#%%
import re
import numpy as np
import matplotlib.pyplot as plt
from scipy.io import loadmat

# -------------------------------------------------------------- params
T_PLOT   = 600.0
DX       = 1.0
L_DOM    = 600.0
H0       = 10.0
WLEVFILE = "wlev.mat"
VELFILE  = "vel.mat"
BOTFILE  = "bot.txt"

# -------------------------------------------------------------- helpers
def parse_swash_time(key):
    """SWASH variable name → simulation time in seconds, or None."""
    m = re.search(r"_(\d{2})(\d{2})(\d{2})(?:_(\d{1,3}))?$", key)
    if not m:
        return None
    h, mn, s, sub = m.groups()
    t = int(h)*3600 + int(mn)*60 + int(s)
    if sub:
        t += int(sub) / 10**len(sub)
    return t

def pick_snapshot(matfile, prefixes, t_target):
    """Open a SWASH .mat output, find variables whose names start with any
       of the given prefixes (case-insensitive), and return the snapshot
       closest to t_target along with the actual time."""
    data = loadmat(matfile)
    keys = [k for k in data.keys()
            if any(k.lower().startswith(p.lower()) for p in prefixes)]
    if not keys:
        raise SystemExit(f"No variables matching {prefixes} in {matfile}.  "
                         f"Got keys: {list(data.keys())}")
    times = np.array([parse_swash_time(k) for k in keys], dtype=float)
    order = np.argsort(times)
    keys, times = [keys[i] for i in order], times[order]
    idx = int(np.argmin(np.abs(times - t_target)))
    return np.array(data[keys[idx]]).ravel(), times[idx], keys[idx]

# -------------------------------------------------------------- load
zb       = np.loadtxt(BOTFILE).ravel()
x        = np.arange(zb.size) * DX
bed_z    = -zb

eta, t_eta, key_eta = pick_snapshot(WLEVFILE, ["Watl", "watl"], T_PLOT)
# SWASH names for the x-velocity vary across versions:
#   SWASH 11.x : 'vel_x_<time>'   (depth-averaged), plus 'vel_k1_x_<time>',
#                'vel_k2_x_<time>', ... for each layer.
#   Older     : 'Velkx_<time>', 'Velx_<time>', 'Vksixs_<time>', 'Vx_<time>'.
u,   t_u,   key_u   = pick_snapshot(VELFILE,
    ["vel_x_", "Velkx", "Velx_", "Vksix", "Vx_"], T_PLOT)

print(f"plotting at t ≈ {t_u:.2f} s   ('{key_eta}', '{key_u}')")
if abs(t_u - t_eta) > 1.0:
    print(f"warning: η and u snapshots are {abs(t_u-t_eta):.1f} s apart")

# -------------------------------------------------------------- plot
fig, (ax_eta, ax_u) = plt.subplots(
    2, 1, figsize=(6,6), sharex=True, dpi=300,
    gridspec_kw={"height_ratios": [1.3, 2.0], "hspace": 0.08},
)

# --- top: bathymetry + free surface (context)
bed_bottom = -H0
ax_eta.fill_between(x, bed_z, bed_bottom, color="wheat", alpha=1.0)
wet = eta > bed_z + 1e-6
ax_eta.plot(x, eta, color="#065A82", lw=1.5, label=f"η(x)")
ax_eta.plot(x, bed_z, color="#5A3A24", lw=0.9, alpha=0.9)
ax_eta.axhline(0., color="#5B6B7C", lw=0.8, ls="--", alpha=0.6)
ax_eta.set_ylabel("z  [m]")
ax_eta.set_ylim(bed_bottom, 2.5)
ax_eta.set_xlim(0., L_DOM)
ax_eta.grid(alpha=0.25)
ax_eta.legend(loc="best", fontsize=9)
ax_eta.set_title(f"Instantaneous velocity at t = {t_u:.1f} s",loc='left')

# --- bottom: u(x)
ax_u.axhline(0., color="#5B6B7C", lw=0.8, ls="-", alpha=0.5)
ax_u.plot(x, u, color="#E76F51", lw=1.8, label="u(x)  (depth-averaged)")
# fill positive/negative regions to make direction obvious

ax_u.set_xlabel("x  [m]")
ax_u.set_ylabel("u  [m/s]")
ax_u.set_xlim(0., L_DOM)
ax_u.grid(alpha=0.25)
ax_u.legend(loc="best", fontsize=9)

fig.tight_layout()
fname = f"u_t{int(round(t_u)):04d}.png"
fig.savefig(fname, dpi=140)
print(f"wrote {fname}")
plt.show()
# %%
