"""
plot_u.py
Plot the instantaneous velocity u(x) over the bathymetry at a chosen time.

Reads:
    bot.txt   — bottom level (positive downward, generated by make_bathy.py)
    vel.txt   — BLOCK ASCII output from SWASH (LAYOUT 3, VEL)
                each row is one time step: nx values of velocity [m/s]

Usage:
    edit T_PLOT below, then `python3 plot_u_snapshot.py`
"""
#%%
import numpy as np
import matplotlib.pyplot as plt

# ── params (must match input.sws) ──────────────────────────────────────
T_START  = 100.0    # first output time [s]  (OUTPUT 000100.000)
DT_OUT   = 1.0      # output interval   [s]
DX       = 1.0      # grid spacing      [m]
T_PLOT   = 400.0    # requested snapshot time [s] (relative to T_START)
T_PLOT   = T_START + T_PLOT  # absolute time to plot

# ── bathymetry ──────────────────────────────────────────────────────────
bathy = np.loadtxt("bot.txt").ravel()
x     = np.arange(bathy.size) * DX
nx    = len(bathy)

# ── helper: read SWASH BLOCK ASCII (any number of values per line) ──────
def read_block(path):
    """Read a SWASH BLOCK ASCII file into a flat float array."""
    with open(path) as f:
        return np.fromstring(f.read(), sep=' ')

# ── water level:  wlev.txt ────────────────────────────────────────────
vals   = read_block("wlev.txt")           # flat 1-D
n_times = len(vals) // nx
wlev   = vals.reshape(n_times, nx)        # (n_times, nx)
times  = T_START + np.arange(n_times) * DT_OUT
it = int(np.argmin(np.abs(times - T_START - T_PLOT)))

# ── velocity:  vel.txt ────────────────────────────────────────────────
# SWASH BLOCK layout per time step with 'VELK VEL':
#   VELK: 2*NLEV rows alternating  u_k1, v_k1, u_k2, v_k2, ..., u_kN, v_kN
#   VEL:  1 row  — depth-averaged velocity magnitude
#   total rows per time step = 2*NLEV + 1
# (v is zero in 1D but SWASH always writes both components)
vals_v     = read_block("vel.txt")
rows_per_t = len(vals_v) // (n_times * nx)   # = 2*NLEV + 1
NLEV       = (rows_per_t - 1) // 2           # auto-detected number of layers
vel_raw    = vals_v.reshape(n_times, rows_per_t, nx)

velk_u = vel_raw[:, 0:2*NLEV:2, :]   # (n_times, NLEV, nx) cross-shore velocity
velk_v = vel_raw[:, 1:2*NLEV:2, :]   # (n_times, NLEV, nx) along-shore (0 in 1D)
vel    = vel_raw[:, 2*NLEV,     :]   # (n_times, nx)        depth-averaged magnitude

# ── quick check ─────────────────────────────────────────────────────────
print(f"x      : {x.shape}   {x[0]:.0f} – {x[-1]:.0f} m")
print(f"times  : {times.shape}   {times[0]:.1f} – {times[-1]:.1f} s")
print(f"wlev   : {wlev.shape}")
print(f"NLEV   : {NLEV}   (auto-detected)")
print(f"velk_u : {velk_u.shape}   (n_times, n_layers, nx) cross-shore")
print(f"vel    : {vel.shape}    (n_times, nx) depth-averaged magnitude")

#%% PLOT
fig, ax = plt.subplots(figsize=(6, 3),dpi=300)

ax.plot(x, vel[it,:], color="red", lw=1.8, label=f"u(x)  at t = {T_PLOT:.1f} s")
ax.axhline(0., color="gray", lw=0.8, ls="--", alpha=0.7, label="SWL")

ax.set_xlabel("x  [m]")
ax.set_ylabel("u  [m/s]")
ax.set_title(f"Cross-shore velocity at t = {T_PLOT:.1f} s",loc='left')
ax.set_xlim(0., 600)
ax.set_ylim(-1.5, 1.5)
ax.legend(loc="best", fontsize=9)
ax.grid(alpha=0.25)
fig.tight_layout()
fname = f"u_t{int(round(T_PLOT)):04d}.png"
fig.savefig(fname, dpi=140)
print(f"wrote {fname}")
plt.show()